spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?useUnicode=true&characterEncoding=utf-8&serverTimeZone=Shanghai
    username: root
    password: 234009
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.liufu: debug

mybatis:
  configuration:
    map-underscore-to-camel-case: true